all:		Office

Office:		Patient.cpp Treatment.cpp Doctor.cpp Driver-4.cpp
			g++ -Wall -o office Patient.cpp Treatment.cpp Doctor.cpp Driver-4.cpp

run:		office
			./office	

clean:		office
			rm -f office